<?php

$items = array(
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis interdum bibendum pellentesque. Vestibulum vel mollis augue. Mauris ullamcorper mattis lorem, ac pellentesque neque tincidunt vel. Phasellus porta, nisi a aliquet scelerisque, dolor tellus condimentum elit, ac aliquam neque lectus vitae dui. Nulla dignissim laoreet nisi vitae posuere. Sed nec urna eget est interdum efficitur. Pellentesque consequat dui sit amet odio volutpat placerat. Fusce finibus ex id tellus tempor molestie. Morbi purus tellus, faucibus nec ipsum ut, fringilla gravida risus. Sed faucibus nunc efficitur condimentum lacinia. Nulla cursus accumsan turpis, ac laoreet felis varius sed. Curabitur eros felis, condimentum id mollis a, dictum ut ante. Aenean non purus scelerisque, congue dui id, accumsan lorem. Quisque dictum nunc sit amet ornare rutrum. Donec dignissim tempus nunc, nec placerat lectus facilisis in.',
    'Sed dapibus odio nisi, in consequat est sagittis id. Praesent porttitor, lacus quis blandit aliquet, velit nunc tincidunt erat, sit amet scelerisque ex est sed velit. Mauris vel eros diam. Nulla cursus purus diam, malesuada egestas tellus vestibulum ut. Donec tincidunt massa mi, ut congue nulla posuere vel. Morbi ac lorem augue. Donec ornare ullamcorper lorem. Vivamus tincidunt ornare augue nec rhoncus. Donec facilisis molestie rhoncus. Morbi in justo non nisl faucibus pellentesque sed condimentum sem. Proin tempus nunc neque, et iaculis mauris consectetur a.',
    'Suspendisse vitae venenatis magna. Aenean non eros nibh. Ut vel vulputate nibh. Aenean vitae leo dui. Quisque quis aliquam tellus. Praesent egestas volutpat leo vitae tincidunt. In quis purus ut elit consequat ornare ut tempor diam. Mauris mauris est, commodo sit amet libero in, mattis aliquam libero. Aenean maximus posuere nunc ac scelerisque. Praesent vel tempor odio, vitae placerat risus.',
    'Pellentesque convallis auctor tempus. Curabitur id fermentum libero. Fusce feugiat sagittis libero, vitae consectetur eros pharetra quis. Curabitur vehicula congue iaculis. In scelerisque leo at scelerisque commodo. Sed ante purus, gravida egestas hendrerit eu, vestibulum nec tortor. Fusce tincidunt bibendum velit, in tempor nisi feugiat a. Suspendisse viverra gravida arcu ac euismod. Vivamus egestas ullamcorper ligula non mollis. Vivamus sit amet urna ornare, sollicitudin quam a, sodales mi. Curabitur tincidunt erat ac pulvinar feugiat. Nullam magna ligula, maximus non quam quis, dictum condimentum sapien. Curabitur congue leo id justo pellentesque ultrices. Nulla nibh massa, aliquam id tempor eget, maximus in massa.',
    'Nunc vitae magna in velit scelerisque ultrices. Nullam sed turpis nisl. Nunc justo odio, vestibulum sit amet scelerisque in, scelerisque vel justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis metus ut purus suscipit tempus. Phasellus mi nisi, varius sed lorem at, congue semper arcu. Nunc vitae enim eget orci suscipit dapibus fringilla id lectus. Suspendisse vestibulum tellus eu massa iaculis, vitae convallis nisi tristique. Ut fermentum vestibulum faucibus. Quisque dictum egestas mi, ac commodo neque fermentum ac. Vestibulum aliquam dolor ut nunc efficitur vehicula. Nunc sodales mattis sem sed feugiat. In hac habitasse platea dictumst. Integer leo urna, dictum vel odio eu, facilisis mattis sem. Nullam finibus placerat erat, et accumsan dui mattis a. Nunc fringilla nunc et tortor tincidunt, nec tristique felis blandit.',
    'Curabitur varius quam quis fermentum tincidunt. Sed egestas enim at metus ornare molestie. Phasellus tincidunt magna ante, nec fringilla dolor egestas quis. Proin sit amet erat leo. Praesent tincidunt nunc id nulla pellentesque, ultricies pulvinar lorem imperdiet. Praesent egestas ipsum sed tellus lacinia, eget placerat nibh elementum. Integer aliquet dolor in lorem euismod pellentesque. Etiam porttitor feugiat porttitor. Proin posuere risus et tristique gravida. Nullam commodo justo in eros hendrerit, ut varius justo dictum. Maecenas ac sem in lorem porttitor scelerisque. Suspendisse pulvinar sollicitudin leo quis ultricies.',
    'Nulla eu dignissim neque, eget venenatis magna. Donec quis ultrices enim, in scelerisque nisi. Aliquam erat volutpat. Curabitur eleifend blandit nisl id commodo. Proin commodo, risus a eleifend vehicula, lacus lacus eleifend sem, nec euismod nulla sem nec dolor. Praesent rhoncus consectetur convallis. Sed in sem nec nisi efficitur tristique ac quis augue. Pellentesque laoreet varius risus, a condimentum dolor suscipit porta.',
    'Vestibulum faucibus ligula ac arcu rutrum, in pulvinar nulla blandit. Vivamus at neque vulputate, convallis dui sit amet, accumsan erat. Phasellus ut tortor nec lacus semper laoreet sit amet et enim. In eu hendrerit risus. Nullam sapien eros, gravida a faucibus at, dictum a augue. Sed facilisis porta tincidunt. Proin hendrerit fermentum eros, sed ornare nisl bibendum sed.',
    'Proin ipsum ante, finibus nec sem facilisis, tristique viverra ex. Maecenas volutpat blandit iaculis. Donec vel ornare felis. Morbi turpis est, maximus quis malesuada vel, gravida sit amet ante. Vivamus facilisis feugiat orci nec ultricies. Ut pellentesque venenatis ex. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis magna dui, pulvinar non maximus at, fermentum quis nisl. Ut quis commodo nisi, nec scelerisque felis. Praesent iaculis rhoncus tortor vitae commodo. Integer nisl purus, malesuada consectetur libero vel, ultricies accumsan mauris. Proin nec imperdiet lorem. Quisque non pellentesque leo.',
    'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras iaculis scelerisque sem id varius. Nullam sed volutpat sapien, eget condimentum ipsum. Nunc lobortis ligula ac sapien sagittis, condimentum sodales lacus ultrices. Nullam volutpat congue elementum. Phasellus nulla arcu, varius vel risus quis, tincidunt aliquet lacus. Nullam eros massa, lobortis a orci sit amet, vestibulum sodales ante. Pellentesque posuere consequat metus et gravida.',
    'Etiam fringilla metus quis risus ullamcorper pretium eget ut dolor. Aenean nisi sapien, tincidunt quis lectus id, facilisis accumsan nunc. Proin et velit molestie orci aliquam pharetra sit amet laoreet sapien. Nullam vitae libero at leo egestas eleifend. Cras porta gravida imperdiet. Quisque et pretium enim. Nam vitae nibh vitae lorem mattis egestas at porta risus. Phasellus sed sapien gravida, feugiat augue vel, gravida ligula. Nulla semper ex turpis, eu pharetra enim tempus at. Nulla facilisi. Aenean tempor urna justo, sed aliquet purus molestie ut. Phasellus auctor sit amet diam eu facilisis.',
    'Phasellus elit lectus, imperdiet sit amet rutrum sed, porta sed elit. Phasellus dapibus interdum tristique. Sed gravida nulla at suscipit volutpat. Nulla accumsan vitae turpis vitae aliquam. Aenean cursus id orci nec placerat. Proin id leo ante. Maecenas feugiat ut nunc eu tincidunt. Mauris ut accumsan nisl. Nulla consequat interdum vehicula. Morbi tempus sed lacus quis pellentesque.',
    'Nulla facilisi. Aliquam faucibus tempor nunc vel tristique. Donec nec quam eleifend, bibendum nibh vel, commodo mi. Aliquam tempor, tellus sit amet volutpat porttitor, eros arcu accumsan nunc, vitae placerat felis sapien in mi. Nullam sed venenatis augue. Etiam pretium augue vitae iaculis pretium. Aliquam sit amet accumsan dui, sed tincidunt risus. Mauris elementum pulvinar massa, vel molestie lorem elementum et. Donec sit amet mauris non nulla dictum rhoncus sed sit amet enim. Etiam ornare a purus ut venenatis. In hac habitasse platea dictumst. Suspendisse potenti. Donec nibh velit, vulputate eget metus quis, facilisis iaculis orci.',
    'Aenean ac efficitur velit. Nam et rhoncus ante. Praesent tempor in risus non ultrices. Nam eleifend, urna sit amet vestibulum venenatis, est mauris ultricies ante, quis fermentum eros ligula vitae lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce lacinia neque ligula, et vestibulum nisi congue id. Cras velit sem, tempor ac consectetur in, efficitur ut lacus. Suspendisse ut vulputate felis. Fusce vitae tellus ac enim tincidunt vehicula. Integer sit amet libero mauris. Donec nec euismod neque. Nullam quam risus, aliquam eu congue sed, ultrices id odio. Donec fringilla sapien eget condimentum venenatis. Mauris rutrum enim eu sem semper, vel vehicula lacus cursus. Duis consequat eu felis in posuere.',
    'Sed auctor lectus sit amet egestas fringilla. Cras ut fringilla ex. Curabitur cursus nulla in elit viverra consectetur nec et velit. Etiam hendrerit cursus ante eget viverra. Quisque in magna ligula. Morbi condimentum orci ultrices lorem ultrices, sed malesuada urna viverra. Integer fringilla efficitur dapibus. Ut nec ex est.',
    'Donec non pellentesque dui, a egestas lectus. Fusce dapibus sagittis massa, at fermentum mauris scelerisque at. Fusce quis ipsum ut nulla ultrices placerat. Integer luctus in lacus in varius. Donec fringilla tempor elit aliquam rutrum. Proin erat nunc, condimentum ut leo eu, tristique dignissim dui. Quisque convallis vel nisi pretium tincidunt. Aenean quis sollicitudin nisi.',
    'Aliquam erat volutpat. Mauris a ipsum semper, consequat nulla vel, rhoncus libero. Vestibulum ultricies est a massa gravida, non pulvinar dolor viverra. Integer nec est magna. Maecenas nisl est, fringilla id mi eu, consectetur rhoncus sem. Nulla sapien risus, bibendum ac dui vel, tincidunt congue nisi. Sed vitae condimentum lacus, et elementum neque. Vivamus efficitur ex ligula, a pulvinar turpis condimentum quis. Sed fringilla facilisis felis vel convallis. Aliquam cursus magna a neque tincidunt ornare. Quisque elementum enim in erat eleifend, vitae varius elit tempor. Sed quis ultrices elit, sit amet tincidunt libero. Nunc sit amet eros a dolor mattis venenatis vitae non ex. Aliquam id lorem neque. Ut lacus elit, bibendum feugiat iaculis rhoncus, mattis ac nunc. Vivamus scelerisque feugiat gravida.',
    'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent purus mauris, malesuada quis vestibulum ut, lobortis a purus. Nulla maximus facilisis aliquet. Nullam tincidunt elit nulla, ac tincidunt enim pellentesque eu. Fusce laoreet dui erat, non efficitur dui rhoncus rutrum. Donec imperdiet placerat velit, eu rutrum ipsum cursus eget. Quisque nec nibh sed orci pellentesque convallis quis sit amet ligula.',
    'Vivamus iaculis nulla condimentum, viverra lorem vestibulum, ornare urna. Donec pulvinar maximus metus, maximus congue ex bibendum ut. Cras at sodales lectus, sed scelerisque velit. Duis varius gravida ultricies. Praesent nisi massa, dictum quis felis ac, ultricies tempor eros. Nulla pellentesque arcu sed erat tempus, at sodales felis accumsan. Sed laoreet sem non tellus rutrum, eget finibus libero posuere. Praesent ipsum lectus, pharetra aliquam felis sit amet, dictum volutpat turpis. Duis iaculis ligula mauris, sit amet finibus lorem aliquam nec. Etiam efficitur erat nec lacus venenatis, et bibendum mi tempor. Suspendisse potenti.',
    'Sed luctus interdum felis a sagittis. Sed ultrices felis tristique ex faucibus accumsan. Etiam tincidunt ultrices orci, eu rutrum metus rhoncus vitae. Nunc eu lobortis odio. Nunc mattis vel lacus non tempor. Nam ut fringilla mi. Duis sit amet aliquam tortor. Ut sollicitudin, ligula vel pellentesque blandit, diam arcu iaculis mi, et finibus sem ipsum sit amet diam. Mauris ut lectus auctor, viverra tortor in, auctor lorem. Sed pellentesque magna sed enim fringilla vehicula. Cras placerat pretium velit, sed tempor ex venenatis vel.',
    'Vivamus laoreet lectus nec enim aliquam consectetur. Pellentesque ac nisl ipsum. Aliquam maximus odio eu lacus convallis dignissim. Maecenas mollis turpis eu faucibus auctor. Cras nulla nibh, dignissim eu interdum sed, sollicitudin sed odio. Donec porttitor felis gravida tincidunt sagittis. In quis orci sit amet mauris lobortis egestas. Aenean tincidunt ipsum eget magna hendrerit, id vestibulum lectus facilisis. Sed purus massa, imperdiet id dolor eget, varius finibus quam. Phasellus id euismod est.',
    'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis vel felis sagittis, tempor nibh nec, semper neque. Pellentesque commodo ipsum nulla. Cras pretium nisl eget odio efficitur cursus. Duis sit amet euismod diam. Ut semper augue sed orci aliquet consectetur sit amet et mi. Sed vel luctus elit. Nulla ullamcorper hendrerit ullamcorper. Nam auctor hendrerit purus vel dictum. Sed interdum libero quis neque accumsan, vel commodo metus venenatis. Maecenas in felis rhoncus, rhoncus quam eget, vehicula leo. Fusce fringilla elit non congue faucibus. Praesent molestie fermentum nulla, elementum blandit nisl cursus sed.',
    'Nulla porta nunc ac nulla tempus facilisis a nec est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras tempor sapien vel turpis iaculis, non egestas erat vestibulum. Duis condimentum sapien posuere orci dignissim, eget fringilla purus bibendum. Etiam ullamcorper, felis quis accumsan pellentesque, felis erat dictum purus, vel tristique neque nisl id dui. Sed sit amet pretium nunc. Nulla eleifend felis odio, ut elementum mi sagittis eget.',
    'Nam eget est ac urna laoreet efficitur. In ut vulputate diam. Cras ullamcorper accumsan libero, sit amet malesuada tortor fringilla eget. Donec et sem sed dui vestibulum varius. Aliquam tristique accumsan urna, id consequat nulla faucibus in. Vestibulum nec sem venenatis, suscipit magna sit amet, auctor dui. Morbi posuere facilisis ligula. Proin enim metus, eleifend nec neque ut, ornare dignissim nunc. Aenean non gravida augue. Sed tincidunt tellus id mauris feugiat, at mollis nisl semper. Nam auctor augue quis quam lobortis blandit. Praesent dictum diam dui, a finibus mauris eleifend id. Vestibulum vel velit eu mi elementum tincidunt.',
    'Donec non dolor non ligula feugiat sollicitudin. Sed diam velit, aliquam sit amet leo nec, scelerisque imperdiet neque. Phasellus iaculis ex et lorem sollicitudin, sit amet egestas tortor consectetur. Nulla lobortis lacus a nibh mattis lacinia. Aliquam feugiat in mi quis pharetra. Donec enim ipsum, tempor nec sagittis mattis, facilisis vel lectus. In eget suscipit ligula. Etiam finibus pretium risus, ac cursus lectus feugiat eget. Sed commodo ut odio non iaculis. Phasellus consectetur faucibus facilisis. Sed eget ipsum at lectus venenatis viverra ac at felis. Nullam tincidunt a nisl et vulputate. Sed quis ullamcorper lorem, vitae bibendum nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    'Integer ultrices mauris a libero lobortis, ac auctor libero vestibulum. Aliquam vulputate molestie quam, a mollis augue iaculis sit amet. Curabitur nec tincidunt turpis. Curabitur egestas eros ac tortor pulvinar, eget malesuada urna interdum. In lacus neque, sodales in odio non, venenatis ultrices nisi. Donec eu fringilla justo. Praesent eget tempus sapien. Aenean pellentesque maximus urna, eu pharetra arcu lacinia vel. Proin hendrerit vel sem at varius. Aliquam interdum erat accumsan velit tempus imperdiet sit amet id massa. Nunc dictum metus dui, id gravida diam gravida vitae. In tincidunt arcu non nulla porta, sit amet tincidunt massa pellentesque.',
    'Donec mollis vitae arcu quis ultrices. Etiam auctor, orci nec maximus porttitor, diam leo aliquam eros, et tincidunt odio lacus id justo. Fusce ultricies ultrices vestibulum. Nulla cursus commodo tincidunt. Aenean risus sapien, condimentum eleifend molestie vitae, aliquam eu ante. Phasellus accumsan tortor nec ligula vestibulum suscipit. Aliquam ut scelerisque quam, ut consectetur ipsum.',
    'Curabitur eget justo massa. Integer et ligula sagittis, vehicula tellus sit amet, blandit enim. Integer ex diam, congue in vehicula non, bibendum eget massa. Fusce tincidunt pulvinar dignissim. Integer convallis vehicula sem sed feugiat. Proin in turpis at turpis maximus ultricies id vel metus. In eget aliquet nunc, nec suscipit lorem. Fusce mauris neque, dapibus at mi nec, consequat finibus magna.',
    'Suspendisse et congue justo. Maecenas enim justo, tincidunt quis accumsan et, pharetra sit amet ipsum. Aliquam erat volutpat. Duis id molestie urna. Donec sit amet molestie tortor. Curabitur volutpat tempor justo nec aliquam. Phasellus mattis orci eget dictum feugiat. In pellentesque magna ligula, id volutpat erat tempus quis.',
    'Quisque eu nisl nec nisl posuere varius. Phasellus facilisis est eget sem ultrices pellentesque. Vestibulum rutrum tincidunt nisi, eget ultrices odio suscipit a. Aliquam gravida urna turpis, in elementum quam iaculis a. Fusce consequat rutrum ex, convallis sollicitudin ligula scelerisque vitae. Cras maximus diam eget dui volutpat, et bibendum justo elementum. Nullam vehicula lorem eu tortor dapibus, imperdiet feugiat leo venenatis. Curabitur tortor augue, dapibus quis fringilla id, tempor sed tortor. Fusce ut vehicula augue, scelerisque accumsan augue.',
);

if ($value > 1000) {
    $value = 1000;
} else if ($value < 0) {
    $value = 1;
}

$result = '';
for ($i = 0; $i < $value; $i++) {
    shuffle($items);

    if ($i) {
        $result .= "\n\n";
    }

    $result .= $items[0];
}
